name: Build Docker Images
on:
  push:
    branches:
      - main
      - 'feat/*'
    tags:
      - '*'
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker Image
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Depot
        uses: depot/setup-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Metadata (Debian)
        id: meta_debian
        uses: docker/metadata-action@v5
        with:
          bake-target: debian
          images: |
            ghcr.io/azuracast/icecast-ac
          flavor: latest=false
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=raw,value=latest-debian,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,event=tag
      
      - name: Build Docker Metadata (Alpine)
        id: meta_alpine
        uses: docker/metadata-action@v5
        with:
          bake-target: alpine
          images: |
            ghcr.io/azuracast/icecast-ac
          flavor: |
            latest=false
            suffix=-alpine
          tags: |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and push
        uses: depot/bake-action@v1
        with:
          push: true
          files: |
            ./docker-compose.yml
            cwd://${{ steps.meta_debian.outputs.bake-file-tags }}
            cwd://${{ steps.meta_debian.outputs.bake-file-labels }}
            cwd://${{ steps.meta_alpine.outputs.bake-file-tags }}
            cwd://${{ steps.meta_alpine.outputs.bake-file-labels }}